#' fgsea wrapper
#'
#' This function is a convenient wrapper for the
#' \code{\link[=fgsea]{fgsea::fgsea()}} function.
#'
#' @inheritParams .decoupler_mat_format
#' @inheritParams .decoupler_network_format
#' @param options A list of named options to pass to
#' \code{\link[=fgsea]{fgsea::fgsea()}}..
#' These options should not \code{include}, \code{pathways} or \code{stats}.
#' @param seed A single value, interpreted as an integer, or NULL.
#'
#' @return A long format tibble of the enrichment scores for each tf
#'  across the conditions. Resulting tibble contains the following columns:
#'  \enumerate{
#'    \item{\code{statistic}}: {Indicates which method is associated with which score.}
#'    \item{\code{tf}}: {Source nodes of \code{network}.}
#'    \item{\code{condition}}: {Condition representing each column of \code{mat}.}
#'    \item{\code{score}}: {Regulatory activity (enrichment score).}
#'    \item{\code{...}}: {Columns of metadata generated by fgsea method.}
#'  }
#' @export
#' @importFrom fgsea fgsea
run_fgsea <- function(mat,
                      network,
                      .source = .data$tf,
                      .target = .data$target,
                      options = list(),
                      seed = 42) {
  regulons <- network %>%
    convert_to_fgsea({{ .source }}, {{ .target }})

  conditions <- colnames(mat) %>%
    set_names()

  set.seed(seed)
  map_dfr(.x = conditions, .f = ~ {
    options <- c(list(pathways = regulons, stats = mat[, .x]), options)
    do.call(what = fgsea, args = options)
  }, .id = "condition") %>%
    mutate(statistic = "fgsea") %>%
    select(.data$statistic, tf = .data$pathway, .data$condition, score = .data$ES, everything()) %>%
    as_tibble() %>%
    `attr<-`(".internal.selfref", NULL)
}
